[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[window]
opacity = 0.9
blur=true

[window.padding]
x = 0
y = 0

[scrolling]
history = 10000

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

